language: python
python: 3.7
dist: xenial
sudo: true
install:
- pip install pipenv
- pipenv install --dev
- pip install pytest-cov
matrix:
  include:
  - script: pytest --cov=./tests
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: heroku
  api_key:
    secure: IZF5hSKsT3kUe7BfbfArLRPTBTW/MdX0o4o4pIhpctMeGAKH7BS3j65k9ozYjiWPnOonrl1zmMk2zVWVvAIlX41Iwj7c9oQB+LR+9mk4hTzoWDMcGqF7wrLhmlOTTg9AOuTyBJggtj7HOiJP2RurjnpM9P9VpHDc+mVFwattHS8Gt6jTtAmsAP/3oPG4WVVwu5KBDQUdlKAP9QVRo8Ews31QNAhvJsHQl4NdfCnNEQ+wTpbCK8Y3mGxCg3FuW488jNoq4hUn9Jy87HjBt6B3tRCYpRLpFdPTatrHO1Af0tD1s4JE2r1SKAL9xZfBxeHDLQSfjP8xE1n+UCaYQsO+9ic+Ndjn9YIAgd6zr2U7Rwx6HZAFm1vfn//IqaIzd3HMtoAxpf+SS25ctO4nAVIQJd+LWsBsEx2lmkK96cupJInsMz/XSBx8SpS2ljkb8B7irmCA+h7KouV/+8LguvNhGlvihpVrZoBZJ69pAe2L6i98Ik7iYkjb+BM1wFtFZEmaa2Za2Rejlwum2fAsGnP7X2t17aa2lad3vnEpYG7n9DmKIyCyxXwTxlvuCPQc0oEDD92hJCYflDIQLscjGtDkgqICFe1zCDAIY7AQM1sBkxBES71VDdY//lU4bZ6vQImXRB2ehDhyMzPcVrhqnPy4vO9tUZ3GolEOpFgpxmq7pqY= 
  on:
    all_branches: true
  app: test-app-stella-dp
