language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install pipenv
  - pipenv install --dev
  - pip install pytest-cov
script:
  - pytest --cov=./tests
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: heroku
  api_key: "%token%"
  app:
    master: stella
    production: stella-dev