language: python
python: 3.7
dist: xenial
sudo: true
install:
- pip install pipenv
- pipenv install --dev
- pip install pytest-cov
matrix:
  include:
  - script: pytest --cov=./tests
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: heroku
  app: test-app655312
  on:
    all_branches: true
  api_key:
    secure: KfwLzEc+1vCnV4cuLdmG/eB0ieVzUWDBJr/3mz0cdc1rKny5Ovlwd360/7Mn1kaEn1Voc36YpRJbjURgRKuUJXbnEcOLWAhhIzxHuXB/FHRCCLAJe6UJwOmwr3HF03pGP2XIF5ZHRf967km+7oQ7H0W19z/DKVQCoqt9HcKtlGPYgaYhSSdX4aCkZSucJlo9JuJfoQdInwgT/08oDOLuKu2DW3hLIdt4+XJsGncanv14hss6Xu9kry7Hg39+9U9RE9gZHoRDOnhmjuuatHTLNketXVgTnweYBEHwPWxKEDoVccH9WJdmARBw5TdAePsbZDluvTG2WND4DqNQfQ90O8VXknb2y1ka3U3iJLkR4kEBwhX37pR8no4Yz63zooQVHxG5x+/4CoPLZIDz9rsXc+K9w7N3HX/GgZeLnCU3KGT5W40UwTlXLnlMhoXN5geatgFP1IKoKhSufeMJR/m5BCTDL0BojJXL3zAjVpZ8bVItwP3NEDJP1GU4bzRSffMU4um4RnC4/JWdho7HRcBNZFNGXy/AZrDhHzziQKS2uT0qnXGgIb3+E+FaU663ZkUP2n0UOhatlxejts02q0anmWNqerm1FQ1xU0nu5d7zd6lQ5WGezIEpEVNlU1NQGb0+RrZpveg5ff+FtHGvlofplKC2xzps1MZYmCiphaG64mk=
