language: python
python: 3.7
dist: xenial
sudo: true
install:
- pip install pipenv
- pipenv install --dev
- pip install pytest-cov
matrix:
  include:
  - script: pytest --cov=./tests
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: heroku
  app: test-app655312
  on:
    all_branches: true
  api_key:
    secure: mmoqkhsrvlGjEfcbuu0QO7C0h0UpZ/KFPj9urncQd1GSw8eZ5GKEaww1l57rk6v1EAd7XpnCGYpL0wc7yEU70LUffDx9njlIW5+UczH4Ab3U2Jb0wSwTY7inp3mURFbElm6mB0TrqnbviOwYsD5KQuN8iGNmHZ625ln5zo6RWZReQt4WXAWB73AvxJzNG2knPo3Vgbqpnvip32pjU5BFYMXaTuOkC/I6IvfP7Pyvnipv99KDrxQ9Fso7zsGASv7Y/2GWeQl3IN84ollD5n1jTa/7liuZxbZwbQLqIP5Dee284Mi36B4D3wz1UgVuTF8bl0rJAQv7g458xwbl5Af8glqkm2itmIXGLZLluj9l30MkkYpMFwUByC2w/6nU+9VKva+REy3B/+NxJTBq46nRH/TWeDNXRLH4eWGrlUKgg31nCIsnKI+Cly2VCdniIYYyp3JprlT3uYNgP73ttwVM5sFWyq+SEYq50wNlA9xhtRf2a96YlfrO9kgpbLuJVdyFKFUa/ROCYwarCs/m2fM2I2ojTmVaecp38MLNJRbzepLXqsgvt2Q0NFRUxBGvTM3V7xeRC0qtNykDuyEy6eBzPdpdStMxHzwPiAVLNWQLbwBG6b1Z/d/4UEPr51dZ6e+tETi7Zh0HzX8olh0ZttfLxVWkf4FoLaoyv98PDwyuCco=
