language: python
python: 3.7
dist: xenial
sudo: true
install:
- pip install pipenv
- pipenv install --dev
- pip install pytest-cov
matrix:
  include:
  - script: pytest --cov=./tests
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: heroku
  api_key:
    secure: PyZIhZvPKUyk+aFJe5NyN4dRiZ8ozlubpiXYnmf9aWkW15pv6wemfVqGQA8qoYiE5V7dPZBoomFxjVb7GsfDqeVdzBmtiTQfNdd25mP6fqU6vcx9+LKOjMW1V08oEw9oMjzrxG0FN0q3hB98+MvuAT6/HIj9i5FX9RMTs6qptKs5BnwwF0FpCUBSsCLZbD2thbIIwfrlm+0JR6XZbra37M24dHq48CrVaFBbH10MWIazOJY0rmImdz5Fq3s76g/9SFfJxBDEz+OXCZNfvmj6Mzv4cGoHleBJW2pqqPX7vouy1W9ct2QMfjSBLbonpk74rSssDZOkAwF2fVHC6mTVqFqq9QQNdY+nffkQRbND0iLsuLfvtefcMQZ9RuLl7su5wGNzKEYmLxtvb8PjKVtPlsd1ZGJoYW9AhvUgNE9OEibdap3IPBUSSK+R9gyYT3UMjZ0fO2RKXvLDpagi3bbpvXKk0JXxJ74uFoIHvw3t/Ib7+OKABQKq7fnn69F/1gNWZqRgCqR+K8Ydf84hLpgz/pf4f6AzHKbX3C1mItEDvzjSFRC25QX2k6WQLKhU3ZnMmDn0Uo/OSfhAdCWKo6puBhEyGS1in0FKcEH/Ki0p6r55v1HvlR0Df0L4ayUt9DK986Pir3v4B7rgGXcdqY5rGMJnHyNLWYFcBjHfRe/GT9M=
  on:
    all_branches: true
