language: python
python: 3.7
dist: xenial
sudo: true
install:
- pip install pipenv
- pipenv install --dev
- pip install pytest-cov
matrix:
  include:
  - script: pytest --cov=./tests
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: heroku
  on:
    all_branches: true
  app: test-app-dp-dp
  api_key:
    secure: qEI5ym++PeNbGkA1LMiQ+OgOKPA7hbMLlZACzO3/C91dADf1x6ggOpWeMZB8ZuPbAP632w0GNTe4VjM8G02K7ZwprmzU4A1Q+dO6CRkl5PL03qFhRxNs/8xSKnqh61M10h5W5As72aoj7gYsg1ZWe++T6BCI0pkR/ztbQhBxB1OMsqXIlMLNQSoW23kcT3gWm0t3Q8IwFl7n2613kT+0NeUnhBYxqkl10y1ds01wSGePAoNhOLNOPRyWjgYM8VYNb3us8a9DIQJkDgZaOilNME4Bh+Qpe+95CHFlXOuYsSSRoUq+0Rk0f0rrUj7X3j9XTOCY1pf9uJFhEFySZ7M4nlJnd7zxVkpfTC5q4JhebDrArRQaV/NVocWyPzxoZ+AxHvfk23YJztS0a1JrFw+A4hjrt5lAcwiIe7oGYdvmUQLOanBcORSZxmaLiQ5Tv1zDYg+FGHEOCAxQacGuZ7FVRBRiKlWL6smMcyM+IuhL/Ex1kUkrrNowwJYOeMEfFHFR3JtvLn10lCi9CADReq31YEJt92K834MO13+paZObiqZETfqy0Dquj5sLeJAel/wK1Rth+y564AMyEpPjgLYMw0QfX/kHRN9Jik4FCOH+zmzJk30Ubic3DbyH4sfQRMGppQKBwMT9H850ngkt3nd0HN9Q5pc6KKeCT0CH73kd4pk=
