language: python
python: 3.7
dist: xenial
sudo: true
install:
- pip install pipenv
- pipenv install --dev
- pip install pytest-cov
matrix:
  include:
  - script: pytest --cov=./tests ./tests
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: heroku
  app: test-app655312
  on:
    all_branches: true
  api_key:
    secure: mmoqkhsrvlGjEfcbuu0QO7C0h0UpZ/KFPj9urncQd1GSw8eZ5GKEaww1l57rk6v1EAd7XpnCGYpL0wc7yEU70LUffDx9njlIW5+UczH4Ab3U2Jb0wSwTY7inp3mURFbElm6mB0TrqnbviOwYsD5KQuN8iGNmHZ625ln5zo6RWZReQt4WXAWB73AvxJzNG2knPo3Vgbqpnvip32pjU5BFYMXaTuOkC/I6IvfP7Pyvnipv99KDrxQ9Fso7zsGASv7Y/2GWeQl3IN84ollD5n1jTa/7liuZxbZwbQLqIP5Dee284Mi36B4D3wz1UgVuTF8bl0rJAQv7g458xwbl5Af8glqkm2itmIXGLZLluj9l30MkkYpMFwUByC2w/6nU+9VKva+REy3B/+NxJTBq46nRH/TWeDNXRLH4eWGrlUKgg31nCIsnKI+Cly2VCdniIYYyp3JprlT3uYNgP73ttwVM5sFWyq+SEYq50wNlA9xhtRf2a96YlfrO9kgpbLuJVdyFKFUa/ROCYwarCs/m2fM2I2ojTmVaecp38MLNJRbzepLXqsgvt2Q0NFRUxBGvTM3V7xeRC0qtNykDuyEy6eBzPdpdStMxHzwPiAVLNWQLbwBG6b1Z/d/4UEPr51dZ6e+tETi7Zh0HzX8olh0ZttfLxVWkf4FoLaoyv98PDwyuCco=
env:
  global:
    secure: miFbYK8FntHGARcN9VnNhtQT9UyuorWGAP7HlEtEEW+kg3+RjSHgKhFbgScCAvxFGOxEEStHXQSDyzzC2U6MDwQMm835p4HcFA3/NtWuFyLv/uojIC6gKSzT1PKtwj+MCKXN/78/sqd4SMpwrezmSudShFE76y5SJ9/l+sjy/xmnQ4MAWuhyKhbbH1jHXurVjrZwHoJ2N/HolK7oLATtX05G0DDV69M4NC+Fj5qE+JH3DtjisvijaqXVShI7sFDzUmyixkawWY6JNU+Was82OuMq3ax++RliuUjfXgus516Q7pJ295Z5hITdM13piKi3HlHveW7cyqLbzs+tzVVWY/oyCkADD25awAF4pwAyq3IdVd81kE6kts0kWDlHuBmhY9cNIRqS7EydxVS9lPo03dWDV/t72tNoGjIWhmeEOdNXFtxCebWJnyZKKfwb/rVz23+rVh2S1CTxIUJKjj3od9p4WdZebZnwLWEkPWCB7NVP8RxsxqQs4WABHsV4C0Q5fRcmzK8sCCg2jAGPHpHzXRyXYJr8SVU/ix0H8rpBHyyJC6FTeV5SJ4pE4FMEN6vXbkaJ3Fj4xYlkxyf/5BwNTjmRFWPUAleb7c3Z5xW/lmTMEV8CjY3+ToChCavGr6c/glOLCypS+urZiN40o8eiUZtDj/a+YDASRdfXFoo/5AU=
