language: python
python: 3.7
dist: xenial
sudo: true
install:
- pip install pipenv
- pipenv install --dev
- pip install pytest-cov
matrix:
  include:
  - script: pytest --cov=./tests
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: heroku
  on:
    all_branches: true
  app: test-app-stella-dp
  api_key:
    secure: WVIIJEgptzLlBiZZ9J6g9Ek+nqX3zR7ohbrH+7tO/CWBQgf78zliR9aGPcXRWtwJyE22uysXKMk/6coJzWMe3xwYT4cpzDB3lrBiiyTusAd267z6Lhpb6fX5Kkm3HkuNPdppzNCAohgWO9VLrxL1Z7WC7PNYvfLJ2po+Xvd4Rf91FIHFfhX+lBu537WUPtI/Sxajd/qQNV6R0LuZwGoimmzDSDfJciO99EqyOEv+dcaH3XwVxpp+rQWN2d17+RCZUXBJaUpdRqnUWD042Iu3fg3F13xETypPpwkl5caFBxRtPgysWtcNdaCLZkhgMXvwVlgivey6g4GUBZtzT+ixhnqfJEDiajwuh93Cujfqh4XzUeqkWy8SM4Iue1FusG0pCvRfT10zuifpDD/AtJNAbemmt43uKOe9b2bh7HiqAChsDms6aB2Kl1/mTSn31FEV5eOU+QDW9IfDII+Lg0VniWQyXXbow8IOSAaz7leYJhAU7uFQLtatgYAjjYAX859TmuDOA7OW4/cE4/h/frQ2ryDtqYv8mTVdEFAVSes4k83MLNsRLZcwdIJ68TvGhnBubWV6Uo8Ffqrdh7BR+/hJyDJUCdrozwF2PTSezRY8fsBoVb9cYfSeYWpHtlrBYD99HiXnYEE7yAvm/qaOI+Eev/eu/meu3e0lgMehFLuk8Mw=
