language: python
python: 3.7
dist: xenial
sudo: true
install:
- pip install -r requirements.txt
- pip install pytest-cov
matrix:
  include:
  - script: pytest --cov=./tests ./tests
notifications:
  email:
    on_success: never
    on_failure: change
before_deploy: ./docker_push
deploy:
  provider: azure_web_apps
  verbose: true
