#!/bin/bash
eval "$(ssh-agent -s)"
chmod 600 ~/deploy_key
echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
ssh-add ~/deploy_key
ssh -i ~/deploy_key -o "StrictHostKeyChecking no" mel@stella-app.northeurope.cloudapp.azure.com pwd
